---
- name: Ensure required packages are installed
  package:
    name: "{{ nfs_required_packages }}"
    state: present
  tags: [ nfs_server ]

- name: Make sure firewalld is running
  systemd:
    state: started
    name: firewalld
  tags: [ nfs_server ]

- name: Enable firewalld and ensure it is not masked
  systemd:
    name: firewalld
    enabled: yes
    masked: no
  tags: [ nfs_server ]

- name: Open firewall ports for NFS server
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  loop: "{{ nfs_firewall_ports }}"
  tags: [ nfs_server ]

- name: Declare NFS services
  set_fact:
    nfs_services: "{{ rhel7_nfs_services if ansible_facts['distribution_major_version'] == '7' else rhel8_nfs_services }}"
  tags: [ nfs_server ]

- name: Create NFS export mount directory {{ nfs_server_directory_path }}
  file:
    path: "{{ nfs_server_directory_path }}"
    state: directory
    mode: 0777
    owner: nobody
    group: nobody
  notify:
    - restart nfs
  tags: [ nfs_exports, nfs_server ]

- name: Create NFS registry shares
  file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
    owner: nobody
    group: nobody
  loop: 
    - "{{ registry_pv_nfs_path }}"
    - "{{ nfs_provisioner_nfs_path }}"
  loop_control:
    label: "Create directory {{ item }}"
  tags: [ nfs_exports, nfs_server ]

- name: SELinux boolean enabled for nfs.
  seboolean:
    name: nfs_export_all_rw
    state: yes
    persistent: yes
  tags: [ nfs_server ]

- name: Deploy NFS exports config to {{ nfs_exports_config }}
  template: 
    src: nfs-exports.j2
    dest: "{{ nfs_exports_config }}"
  notify: reload nfs exports
  tags: [ nfs_exports, nfs_server ]

- name: Starting nfs services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ nfs_services }}"
  loop_control:
    label: "Starting service {{ item }}"
  tags: [ nfs_server ]
